### ISSUE TITLE
yandex

### ISSUE THREAD

**Issue by tagsou** [xnl-h4ck3r/xnldorker#2]
could you add yandex browser

**Comment by xnl-h4ck3r** [comment]
Hey @tagsou. I will look into adding them at some point. Thanks

**Comment by tagsou** [comment]
thank you !

**Comment by xnl-h4ck3r** [comment]
Hi @tagsou. If you use `pip install --upgrade xnldorker` and get v1.1 you will now be able to get links from Yandex. However, I have found that Yandex is soooo bad and even manually will just keep showing the ant-bot page over and over. So, if you do use this source, I would only use if running locally, and also would use `-sb`/`--show-browser`. You will get notifed in the CLI when the ant-bot page is shown. You can then manually respond to that in the browser within the time limit (specifeid by `-abt`/`--antibot-timeout`). If you complete it and you don't want to keep waiting, you can manually type `yandex` in the terminal and press ENTER and it wil resume again. But you will get this ant-bot screen A LOT! Even using Yandex manually seems to show that screen over and over for many users for some reason, even just for normal use. Thanks

**Comment by tagsou** [comment]
Thanks appreciate your effort
