### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by venom26** [xnl-h4ck3r/xnldorker#3]
Hey, 
I hope you are doing well.

Since we are doing Dorking, it would be great if you could add functionality to use proxies with each request. Adding a flag like `--proxy` should work I guess.

Thanks

**Comment by venom26** [comment]
Hey @xnl-h4ck3r 
Thanks for letting me know. I tested this out and looks like proxy feature is not working. I can not see any logs in my proxy for some reason. Can you please look into it.

Thanks

**Comment by venom26** [comment]
Hey @xnl-h4ck3r
Yes, Actually I wanted to check first with my proxy setup if its working or now but my proxy is working fine. So it looks like proxy feature is not working. I can not see any logs in my proxy for some reason. Can you please look into it. Also can you add support for socks5 proxy to it?

Thanks

**Comment by xnl-h4ck3r** [comment]
When I calll it I have to use `-proxy http://192.168.X.X:8080` where `192.168.X.X` is my machine's local IP and 8080 is the Burp port. For some reason 127.0.0.1 doesn't work on my setup, not sure why. Maybe try that too?

**Comment by venom26** [comment]
I guess there is some misunderstanding. I don't mean burp when I say proxy. I mean actually rotating proxies which I can use to bypass captcha's and stuff. Its not working for that.

**Comment by xnl-h4ck3r** [comment]
Ah ok Sorry I did misunderstand completely :/ 
Can I close this issue because I've linked this to a change relating to sending the links to something like Burp? And then could you do me a huge favour and log a new issue and say that you want torotate proxies when making request to the search engines?
Sorry about that. I'm not really sure how to do that at the moment, but please raise it anyway. Thanks!

**Comment by venom26** [comment]
Hey, no worries at all.
I can do that. And as far as I know in Python it's very simple I guess. If you are using requests you can simply use following code
```
import requests

proxies = {
    'http': 'socks5h://localhost:6997',
    'https': 'socks5h://localhost:6997'
}

URL = https://google.com
response = requests.get(URL, proxies=proxies)
```

Thanks
